### ISSUE TITLE
Add support for CSS custom property

### ISSUE THREAD

**Issue by buckle2000** [juliangarnier/anime#449]
Currently, there is no way I can animate CSS custom property with anime.js.

```css
div {
  --progress: 100%;
  transform: scale(var(--progress));
}
```

You can use this to set CSS custom property:

```js
el.style.setProperty('--progress', '40%')
```
