### ISSUE TITLE
Scaling SVG is now blurry in Chrome.

### ISSUE THREAD

**Issue by ndimatteo** [juliangarnier/anime#74]
As of today, all of my SVG elements that I'm scaling with Anime are showing up blurry during the animation in Chrome. See below:

![what](https://cloud.githubusercontent.com/assets/737188/18412710/d6fa02c8-7763-11e6-8f77-6c6144e5d858.gif)

Why is this happening all of a sudden?

**Comment by ndimatteo** [comment]
I can confirm that this doesn't happen in Firefox (v46) or Safari (v9) on a Mac, just with Chrome (v53.0.2785.101)

**Comment by harrynewsome** [comment]
I am experiencing this too.

**Comment by ndimatteo** [comment]
@harrynewsome 

I've found a temporary fix with a CSS hack. Apply the following to your svg:

````css
svg {
  -webkit-backface-visibility: hidden;
  -webkit-transform: translateZ(0) scale(1.0, 1.0);
  transform: translateZ(0);
}
````

Not ideal, but seems to do the trick.
