### ISSUE TITLE
Animation Not Running on Site Load

### ISSUE THREAD

**Issue by Lukas-Batema** [juliangarnier/anime#778]
# Issue
The animation doesn't work on my [Personal Site](https://www.batemadevelopment.com/movement-geography-animation/) when it works on [CodePen](https://codepen.io/fobabett/pen/GmXzVX). I have tried using *webpack* and such, but have not gotten the almost identical code, to work. The only things I really changed are formatting, as well. Here listed below, is my HTML, JS, and CSS. 

#####  HTML
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Movement Animation</title>

    <meta content="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <link rel="stylesheet" type="text/css" href="theme.css" />
  </head>

  <body>
    <script src="index.js"></script>

    <div class="container">
      <div class="bar bar1"></div>
      <div class="ball"></div>
      <div class="bar bar2"></div>
    </div>
  </body>
</html>
```

#####  JS
```javascript
import anime from 'animejs';
import $ from "jquery";

var loop = true;
var easing = 'linear';
var direction = 'alternate';

anime({
  targets: '.ball',
  translateX: 470,
  translateY: 100,
  easing,
  loop,
  direction,
  background: [
    { value: '#573796' },
    { value: '#FB89FB' },
    { value: '#FBF38C' },
    { value: '#18FF92' },
    { value: '#5A87FF' }
  ]
})
var ballTimeline = anime.timeline({
  loop,
  direction
})
var bar2Timeline = anime.timeline({
  loop,
  direction
})
var bar1Timeline = anime.timeline({
  loop,
  direction
})
ballTimeline
  .add({
    targets: '.ball',
    translateY: 100,
    translateX: 470,
    easing
  }).add({
    targets: '.ball',
    translateY: 0,
    translateX: 0,
    easing
  }).add({
    targets: '.ball',
    translateY: '-80',
    translateX: 470,
    easing
  })
bar2Timeline
  .add({
    targets: '.bar2',
    translateY: 100,
    easing,
    background: '#573796'
  }).add({
    targets: '.bar2',
    translateY: 0,
    easing,
    background: '#FB89FB'
  }).add({
    targets: '.bar2',
    translateY: '-100',
    easing,
    background: '#FBF38C'
  })
bar1Timeline
  .add({
    targets: '.bar1',
    translateY: '-80',
    easing,
    background: '#18FF92'
  }).add({
    targets: '.bar1',
    translateY: 10,
    easing,
    background: '#5A87FF'
  }).add({
    targets: '.bar1',
    translateY: 60,
    easing,
    background: '#FF1461'
  })
```

#####  CSS
```css
body {
  background: #000000;
  text-align: center;
}
.container {
  width: 500px;
  display: inline-block;
  transform: translateY(200px);
}
.bar {
  background: #FFFFFF;
  width: 10px;
  height: 100px;
}
.bar1 {
  float: left;
}
.bar2 {
  float: right;
}
.ball {
  background: #FFFFFF;
  width: 10px;
  height: 10px;
  position: relative;
  top: 45px;
  left: 10px;
}
```

Thank you for your kind help!

P.S. The code here, has been updated!
